dataloader_num_workers: 8
pc_size: 4096
model_type: "mdm_st"
pred_offset: true
vis_dir: "vis"
seed: 0
output_dir: ./outputs/dit_${model_config.n_layers}layers_${pc_size}p_${train_dataset.category}_${train_dataset.n_training_frames}frames_pointembed_latent${model_config.latent_dim}_cond_on_first_pc_1gpus_base
train_batch_size: 3
eval_batch_size: 3
num_train_epochs: 50
max_train_steps: 1000 # Lower this to 1000 (It takes 2 hours for one gpu to do 500 steps)
gradient_accumulation_steps: 25
gradient_checkpointing: false
learning_rate: 1e-4
lr_warmup_steps: 100
adam_beta1: 0.9
adam_beta2: 0.999
adam_weight_decay: 1.e-2
adam_epsilon: 1.e-08
max_grad_norm: 1.0
logging_dir: logs
mixed_precision: 'bf16'
report_to: 'wandb'
checkpointing_steps: 100 # Lower this to 250
checkpoints_total_limit: 4
resume_from_checkpoint: latest
validation_steps: 100
# validation_train_steps: 2000
# validation_sanity_check: true
tracker_project_name: 'mcg_baseline'
push_to_hub: false
hub_model_id: null
hub_token: null
model_config:
  latent_dim: 256
  frame_cond: true
  n_layers: 8
  transformer_block: "SpatialTemporalTransformerBlock"
  floor_cond: true
  cond_on_first_pc: true
train_dataset:
  dataset_path: "data_generation/data/3d_primitives/train/h5"
  val_dataset_path: "data_generation/data/3d_primitives/val/h5"
  mode: "diff"
  n_training_frames: 24
  n_frames_interval: 2
  category: "sphere-cube"